theme: jekyll-theme-primer
title: Problem Statement and Motivation
description: Building a model to predict crime in the US
baseurl:
markdown: kramdown
kramdown:
    math_engine: mathjax
    input: GFM
    syntax_highlighter: rouge
